version: "3.9"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "80:80"
#  client:
#    build: ./client
#    container_name: client
#    depends_on:
#      - server
#    ports:
#      - "80:80"