version: "3.9"
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "3000:3000"
  client:
    build: ./client
    container_name: client
    depends_on:
      - server
    ports:
      - "80:80"